# Generated by Django 4.2.7 on 2025-12-22 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('fence_violation', '围栏越界'), ('device_offline', '设备离线'), ('low_battery', '低电量'), ('sos', '主动求救'), ('other', '其他')], max_length=20, verbose_name='预警类型')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('message', models.TextField(verbose_name='消息内容')),
                ('severity', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高'), ('critical', '紧急')], default='medium', max_length=20, verbose_name='严重程度')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('handled', '已处理'), ('ignored', '已忽略')], default='pending', max_length=20, verbose_name='状态')),
                ('is_handled', models.BooleanField(default=False, verbose_name='是否已处理')),
                ('handled_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('handled_note', models.TextField(blank=True, verbose_name='处理备注')),
                ('escalation_level', models.IntegerField(default=1, verbose_name='升级级别')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '预警',
                'verbose_name_plural': '预警',
                'db_table': 'alerts',
                'ordering': ['-created_at'],
            },
        ),
    ]
