# Generated by Django 4.2.7 on 2025-12-22 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='围栏名称')),
                ('center_latitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='中心纬度')),
                ('center_longitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='中心经度')),
                ('radius', models.IntegerField(default=500, verbose_name='半径（米）')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='围栏地址')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('violation_count', models.IntegerField(default=0, verbose_name='越界次数')),
                ('last_violation_time', models.DateTimeField(blank=True, null=True, verbose_name='最后越界时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '电子围栏',
                'verbose_name_plural': '电子围栏',
                'db_table': 'fences',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FenceViolationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_violation', models.BooleanField(default=True, verbose_name='是否越界')),
                ('distance', models.FloatField(blank=True, null=True, verbose_name='距离（米）')),
                ('violation_count', models.IntegerField(default=1, verbose_name='连续越界次数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('fence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violation_logs', to='fences.fence', verbose_name='围栏')),
            ],
            options={
                'verbose_name': '围栏越界日志',
                'verbose_name_plural': '围栏越界日志',
                'db_table': 'fence_violation_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
