# Generated by Django 4.2.7 on 2025-12-22 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fences', '0001_initial'),
        ('devices', '0001_initial'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fenceviolationlog',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fence_violations', to='locations.location', verbose_name='位置'),
        ),
        migrations.AddField(
            model_name='fence',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fences', to='devices.device', verbose_name='设备'),
        ),
        migrations.AddIndex(
            model_name='fenceviolationlog',
            index=models.Index(fields=['fence', '-created_at'], name='fence_viola_fence_i_dad2ba_idx'),
        ),
    ]
