# Generated by Django 4.2.7 on 2025-12-23 18:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='elderlyprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elderly_profile', to=settings.AUTH_USER_MODEL, verbose_name='关联老人用户'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('guardian', '监护人'), ('elderly', '老人'), ('community_admin', '社区管理员'), ('system_admin', '系统管理员')], default='guardian', max_length=20, verbose_name='角色'),
        ),
    ]
