# Generated by Django 4.2.7 on 2025-12-27 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_subscribemessage'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subscribemessage',
            name='unique_user_template',
        ),
        migrations.AlterUniqueTogether(
            name='subscribemessage',
            unique_together={('user', 'template_id')},
        ),
    ]
