# Generated by Django 4.2.7 on 2025-12-22 11:56

import apps.devices.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(default=apps.devices.models.generate_device_id, max_length=64, unique=True, verbose_name='设备ID')),
                ('qr_code', models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name='二维码')),
                ('name', models.CharField(default='定位设备', max_length=50, verbose_name='设备名称')),
                ('device_type', models.CharField(choices=[('smart_bracelet', '智能手环'), ('phone', '手机'), ('tracker', '定位器')], default='smart_bracelet', max_length=20, verbose_name='设备类型')),
                ('status', models.CharField(choices=[('online', '在线'), ('offline', '离线'), ('low_battery', '低电量'), ('error', '故障')], default='offline', max_length=20, verbose_name='状态')),
                ('battery_level', models.IntegerField(default=100, verbose_name='电量')),
                ('last_location_time', models.DateTimeField(blank=True, null=True, verbose_name='最后定位时间')),
                ('last_online_time', models.DateTimeField(blank=True, null=True, verbose_name='最后在线时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('elderly', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='device', to='users.elderlyprofile', verbose_name='关联老人')),
            ],
            options={
                'verbose_name': '设备',
                'verbose_name_plural': '设备',
                'db_table': 'devices',
                'ordering': ['-created_at'],
            },
        ),
    ]
