# Generated by Django 4.2.7 on 2025-12-24 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_alter_device_elderly'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='qr_code',
        ),
    ]
