# Generated by Django 4.2.7 on 2025-12-22 11:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='纬度')),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='经度')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='地址')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location_cache', to='devices.device', verbose_name='设备')),
            ],
            options={
                'verbose_name': '位置缓存',
                'verbose_name_plural': '位置缓存',
                'db_table': 'location_cache',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='纬度')),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='经度')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='地址')),
                ('accuracy', models.FloatField(blank=True, null=True, verbose_name='精度（米）')),
                ('altitude', models.FloatField(blank=True, null=True, verbose_name='海拔（米）')),
                ('speed', models.FloatField(blank=True, null=True, verbose_name='速度（米/秒）')),
                ('heading', models.FloatField(blank=True, null=True, verbose_name='方向角')),
                ('location_type', models.CharField(choices=[('gps', 'GPS'), ('lbs', '基站定位'), ('wifi', 'WiFi定位')], default='gps', max_length=20, verbose_name='定位类型')),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='记录时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='devices.device', verbose_name='设备')),
            ],
            options={
                'verbose_name': '位置记录',
                'verbose_name_plural': '位置记录',
                'db_table': 'locations',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['device', '-recorded_at'], name='locations_device__401d36_idx'), models.Index(fields=['-recorded_at'], name='locations_recorde_2914f4_idx')],
            },
        ),
    ]
